# Generated by Django 3.1.7 on 2021-03-03 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210303_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 3, 12, 18, 47, 943740), verbose_name='date published'),
        ),
    ]
