# Generated by Django 3.1.7 on 2021-03-09 00:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210303_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 0, 26, 53, 244189), verbose_name='date published'),
        ),
    ]
