# Generated by Django 3.1.7 on 2021-03-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='audio',
            field=models.FileField(null=True, upload_to='vocabulary/'),
        ),
    ]
