# Generated by Django 3.1.7 on 2021-03-09 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_vocabulary_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning', models.CharField(max_length=65000)),
                ('native', models.CharField(max_length=65000)),
                ('audio', models.FileField(null=True, upload_to='examples/')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_item', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('vocab', 'Vocabulary'), ('sentence', 'Sentence')], max_length=12)),
                ('example', models.ForeignKey(db_column='example_id', on_delete=django.db.models.deletion.CASCADE, related_name='Material_example_object', to='learn.example')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('draft', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('material', models.ManyToManyField(through='learn.Material', to='learn.Example')),
            ],
        ),
        migrations.AddField(
            model_name='material',
            name='unit',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, related_name='Material_unit_object', to='learn.unit'),
        ),
    ]
